### ISSUE TITLE
MVP release checklist

### ISSUE THREAD

**Issue by kamikazechaser** [grassrootseconomics/cic-ussd#56]
1. Smoke testing

- [ ] Setup Account
- [ ] Send
- [ ] Change Token
- [ ] My Account
- [ ] Pin Options
- [ ] Help

2. Other

- [ ] Translations
- [ ] Voucher Lists Rendering
- [ ] Selected Balance Rendering
- [ ] Data Sync With Graph
- [ ] Statement Rendering

3. Load Testing

- [ ] 100 Concurrent Users Benchmark
- [ ] 500 Concurrent Users Benchmark

4. Chaos Testing

- [ ] Delete Redis USSD DB/Cache

5. Docs

- [ ] Usage
- [ ] Setup
- [ ] Functionality
